! EViewsMgr.f90

! This module contains the COM interfaces of the objects defined in 
! C:\Program Files\EViews 14\x86\EViewsMgr.dll
! Generated by the Fortran Module Wizard on 09/27/24

	MODULE EViewsMgr
		USE IFWINTY
		USE IFCOM
		IMPLICIT NONE
	

		! CLSIDs		
		TYPE (GUID), PARAMETER :: CLSID_Manager = &
			GUID(#755B63C4, #F978, #42B6, &
			  CHAR('8B'X)//CHAR('C5'X)//CHAR('37'X)//CHAR('D0'X)// &
			  CHAR('8C'X)//CHAR('83'X)//CHAR('D9'X)//CHAR('26'X))
		TYPE (GUID), PARAMETER :: CLSID_Application = &
			GUID(#ECF23B84, #8DB9, #4692, &
			  CHAR('AB'X)//CHAR('08'X)//CHAR('10'X)//CHAR('75'X)// &
			  CHAR('8A'X)//CHAR('20'X)//CHAR('94'X)//CHAR('AE'X))

		! IIDs		
		TYPE (GUID), PARAMETER :: IID_IApplication8 = &
			GUID(#03F82B49, #8495, #43EF, &
			  CHAR('AB'X)//CHAR('25'X)//CHAR('33'X)//CHAR('0B'X)// &
			  CHAR('24'X)//CHAR('D1'X)//CHAR('E7'X)//CHAR('D4'X))
		TYPE (GUID), PARAMETER :: IID_IManager = &
			GUID(#3AE114B5, #932A, #4C2D, &
			  CHAR('8B'X)//CHAR('5F'X)//CHAR('64'X)//CHAR('96'X)// &
			  CHAR('A2'X)//CHAR('BB'X)//CHAR('14'X)//CHAR('30'X))
		TYPE (GUID), PARAMETER :: IID_IApplication12 = &
			GUID(#5427E4E3, #F8CB, #451E, &
			  CHAR('B8'X)//CHAR('81'X)//CHAR('87'X)//CHAR('EF'X)// &
			  CHAR('21'X)//CHAR('18'X)//CHAR('FB'X)//CHAR('F9'X))
		TYPE (GUID), PARAMETER :: IID_IApplication = &
			GUID(#6C6D8FC7, #907E, #44A8, &
			  CHAR('BE'X)//CHAR('67'X)//CHAR('E0'X)//CHAR('CF'X)// &
			  CHAR('96'X)//CHAR('3C'X)//CHAR('24'X)//CHAR('27'X))
		TYPE (GUID), PARAMETER :: IID_IApplication11 = &
			GUID(#84A1DB25, #870B, #4587, &
			  CHAR('8F'X)//CHAR('C9'X)//CHAR('B5'X)//CHAR('08'X)// &
			  CHAR('85'X)//CHAR('0A'X)//CHAR('A6'X)//CHAR('F7'X))
		TYPE (GUID), PARAMETER :: IID__IEViewsEvents = &
			GUID(#87F06BEE, #A90C, #4A44, &
			  CHAR('81'X)//CHAR('6A'X)//CHAR('B6'X)//CHAR('9B'X)// &
			  CHAR('EC'X)//CHAR('F0'X)//CHAR('9F'X)//CHAR('41'X))
		TYPE (GUID), PARAMETER :: IID_IApplication10 = &
			GUID(#A3422ABD, #19CB, #45CA, &
			  CHAR('88'X)//CHAR('E2'X)//CHAR('B7'X)//CHAR('AD'X)// &
			  CHAR('B9'X)//CHAR('2D'X)//CHAR('4F'X)//CHAR('B5'X))
		TYPE (GUID), PARAMETER :: IID_IAuthorize = &
			GUID(#B5C27644, #5A38, #477D, &
			  CHAR('9A'X)//CHAR('95'X)//CHAR('6A'X)//CHAR('72'X)// &
			  CHAR('9E'X)//CHAR('54'X)//CHAR('BA'X)//CHAR('07'X))
		TYPE (GUID), PARAMETER :: IID_IApplication9 = &
			GUID(#C4C43C61, #6AAB, #4FAD, &
			  CHAR('BF'X)//CHAR('EB'X)//CHAR('06'X)//CHAR('CC'X)// &
			  CHAR('29'X)//CHAR('73'X)//CHAR('EB'X)//CHAR('66'X))
		TYPE (GUID), PARAMETER :: IID_IApplication13 = &
			GUID(#CDAE5C41, #FC98, #4188, &
			  CHAR('8C'X)//CHAR('F3'X)//CHAR('D4'X)//CHAR('EE'X)// &
			  CHAR('72'X)//CHAR('F9'X)//CHAR('A2'X)//CHAR('8E'X))
		TYPE (GUID), PARAMETER :: IID_IApplication14 = &
			GUID(#E45B6A82, #A882, #4CBE, &
			  CHAR('BE'X)//CHAR('43'X)//CHAR('2E'X)//CHAR('EE'X)// &
			  CHAR('EE'X)//CHAR('F2'X)//CHAR('C1'X)//CHAR('5A'X))

		! Enums		
		! CreateType 
			INTEGER, PARAMETER ::	NewInstance = 0	
			INTEGER, PARAMETER ::	ExistingOrNew = 1	
			INTEGER, PARAMETER ::	ExistingOnly = 2	
		! DataType 
			INTEGER, PARAMETER ::	DataTypeAuto = 0	
			INTEGER, PARAMETER ::	DataTypeScalar = 1	
			INTEGER, PARAMETER ::	DataTypeScalarAlpha = 2	
			INTEGER, PARAMETER ::	DataTypeSeries = 3	
			INTEGER, PARAMETER ::	DataTypeSeriesAlpha = 4	
			INTEGER, PARAMETER ::	DataTypeVector = 5	
			INTEGER, PARAMETER ::	DataTypeVectorCoefficient = 6	
			INTEGER, PARAMETER ::	DataTypeVectorAlpha = 7	
			INTEGER, PARAMETER ::	DataTypeMatrix = 8	
			INTEGER, PARAMETER ::	DataTypeMatrixSymmetric = 9	
			INTEGER, PARAMETER ::	DataTypeTable = 10	
		! EViewsEventType 
			INTEGER, PARAMETER ::	EViewsEventTypeNone = 0	
			INTEGER, PARAMETER ::	EViewsEventTypeAll = 65535	
			INTEGER, PARAMETER ::	EViewsEventTypeStatus = 1	
			INTEGER, PARAMETER ::	EViewsEventTypeError = 2	
			INTEGER, PARAMETER ::	EViewsEventTypeProgramLogAll = 63	
			INTEGER, PARAMETER ::	EViewsEventTypeProgramLogMsgs = 4	
			INTEGER, PARAMETER ::	EViewsEventTypeProgramLogWarnings = 8	
			INTEGER, PARAMETER ::	EViewsEventTypeProgramLogLines = 16	
			INTEGER, PARAMETER ::	EViewsEventTypeProgramLogProfile = 32	
			INTEGER, PARAMETER ::	EViewsEventTypeXLog = 64	
			INTEGER, PARAMETER ::	EViewsEventTypeStatusPlus = 128	
		! LookupReturnType 
			INTEGER, PARAMETER ::	LookupReturnString = 0	
			INTEGER, PARAMETER ::	LookupReturnArray = 1	
			INTEGER, PARAMETER ::	LookupReturnMatrixAsRows = 2	
			INTEGER, PARAMETER ::	LookupReturnMatrixAsColumns = 3	
		! NAType 
			INTEGER, PARAMETER ::	NATypeAsEmpty = 0	
			INTEGER, PARAMETER ::	NATypeAsString = 1	
			INTEGER, PARAMETER ::	NATypeAsExcelNA = 2	
		! SeriesType 
			INTEGER, PARAMETER ::	SeriesTypeAuto = 0	
			INTEGER, PARAMETER ::	SeriesTypeSeries = 1	
			INTEGER, PARAMETER ::	SeriesTypeAlpha = 2	
		! WriteType 
			INTEGER, PARAMETER ::	WriteUpdate = 0	
			INTEGER, PARAMETER ::	WriteOverwrite = 1	
			INTEGER, PARAMETER ::	WriteMergePreferSource = 2	
			INTEGER, PARAMETER ::	WriteMergePreferDestination = 3	
			INTEGER, PARAMETER ::	WriteProtect = 4	

		! Interfaces
		INTERFACE
			!Called by EViews to indicate a specific event.
 			! MEMBERID = 1610678272
 			INTEGER(4) FUNCTION $IEViewsEvents_EViewsEvent($OBJECT, eventType, data)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: eventType	! EViewsEventType
				!DEC$ ATTRIBUTES VALUE	:: eventType
				TYPE (VARIANT), INTENT(IN)	:: data	
				!DEC$ ATTRIBUTES VALUE	:: data
			!DEC$ ATTRIBUTES STDCALL :: $IEViewsEvents_EViewsEvent
			END FUNCTION $IEViewsEvents_EViewsEvent
		END INTERFACE
		POINTER($IEViewsEvents_EViewsEvent_PTR, $IEViewsEvents_EViewsEvent)	! routine pointer
		INTERFACE
			!Returns any previously set instance data.
  			INTEGER(4) FUNCTION IApplication10_GetInstanceData($OBJECT, instanceData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(OUT)	:: instanceData	
				!DEC$ ATTRIBUTES REFERENCE	:: instanceData
			!DEC$ ATTRIBUTES STDCALL :: IApplication10_GetInstanceData
			END FUNCTION IApplication10_GetInstanceData
		END INTERFACE
		POINTER(IApplication10_GetInstanceData_PTR, IApplication10_GetInstanceData)	! routine pointer
		INTERFACE
			!Whether or not EViews is visible
  			INTEGER(4) FUNCTION IApplication10_IsVisible($OBJECT, visible)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				LOGICAL(2), INTENT(OUT)	:: visible	
				!DEC$ ATTRIBUTES REFERENCE	:: visible
			!DEC$ ATTRIBUTES STDCALL :: IApplication10_IsVisible
			END FUNCTION IApplication10_IsVisible
		END INTERFACE
		POINTER(IApplication10_IsVisible_PTR, IApplication10_IsVisible)	! routine pointer
		INTERFACE
			!Set a custom string as instance data.
  			INTEGER(4) FUNCTION IApplication10_SetInstanceData($OBJECT, instanceData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: instanceData	
				!DEC$ ATTRIBUTES VALUE	:: instanceData
			!DEC$ ATTRIBUTES STDCALL :: IApplication10_SetInstanceData
			END FUNCTION IApplication10_SetInstanceData
		END INTERFACE
		POINTER(IApplication10_SetInstanceData_PTR, IApplication10_SetInstanceData)	! routine pointer
		INTERFACE
			!Returns data from an object from the current workfile or from an expression as a 2-dimensional array.
  			INTEGER(4) FUNCTION IApplication8_Get2D($OBJECT, objectName, NAType, naString, objectData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: objectName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: objectName
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				TYPE (VARIANT), INTENT(OUT)	:: objectData	
				!DEC$ ATTRIBUTES REFERENCE	:: objectData
			!DEC$ ATTRIBUTES STDCALL :: IApplication8_Get2D
			END FUNCTION IApplication8_Get2D
		END INTERFACE
		POINTER(IApplication8_Get2D_PTR, IApplication8_Get2D)	! routine pointer
		INTERFACE
			!Returns data from the specified series object in the current workfile as a 2-dimensional array.
  			INTEGER(4) FUNCTION IApplication8_GetSeries2D($OBJECT, seriesName, sampleString, NAType, naString, seriesData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: seriesName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: seriesName
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
			!DEC$ ATTRIBUTES STDCALL :: IApplication8_GetSeries2D
			END FUNCTION IApplication8_GetSeries2D
		END INTERFACE
		POINTER(IApplication8_GetSeries2D_PTR, IApplication8_GetSeries2D)	! routine pointer
		INTERFACE
			!Returns a bit-flag of all EViews events that are currently on.  By default, all event types are turned off.
  			INTEGER(4) FUNCTION IApplication9_GetEventTypeMask($OBJECT, eventTypes)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(OUT)	:: eventTypes	
				!DEC$ ATTRIBUTES REFERENCE	:: eventTypes
			!DEC$ ATTRIBUTES STDCALL :: IApplication9_GetEventTypeMask
			END FUNCTION IApplication9_GetEventTypeMask
		END INTERFACE
		POINTER(IApplication9_GetEventTypeMask_PTR, IApplication9_GetEventTypeMask)	! routine pointer
		INTERFACE
			!Sets which EViews events should be turned on.
  			INTEGER(4) FUNCTION IApplication9_SetEventTypeMask($OBJECT, eventTypes)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: eventTypes	! EViewsEventType
				!DEC$ ATTRIBUTES VALUE	:: eventTypes
			!DEC$ ATTRIBUTES STDCALL :: IApplication9_SetEventTypeMask
			END FUNCTION IApplication9_SetEventTypeMask
		END INTERFACE
		POINTER(IApplication9_SetEventTypeMask_PTR, IApplication9_SetEventTypeMask)	! routine pointer
		INTERFACE
			!Utility function to convert a string array (or range) into a space delimited string.
  			INTEGER(4) FUNCTION IApplication_ArrayToList($OBJECT, nameArray, nameString)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: nameArray	
				!DEC$ ATTRIBUTES VALUE	:: nameArray
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: nameString	! BSTR
				!DEC$ ATTRIBUTES REFERENCE	:: nameString
			!DEC$ ATTRIBUTES STDCALL :: IApplication_ArrayToList
			END FUNCTION IApplication_ArrayToList
		END INTERFACE
		POINTER(IApplication_ArrayToList_PTR, IApplication_ArrayToList)	! routine pointer
		INTERFACE
			!Returns data from an object from the current workfile or from an expression.
  			INTEGER(4) FUNCTION IApplication_Get($OBJECT, objectName, NAType, naString, objectData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: objectName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: objectName
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				TYPE (VARIANT), INTENT(OUT)	:: objectData	
				!DEC$ ATTRIBUTES REFERENCE	:: objectData
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Get
			END FUNCTION IApplication_Get
		END INTERFACE
		POINTER(IApplication_Get_PTR, IApplication_Get)	! routine pointer
		INTERFACE
			!Returns data from multiple series objects in the current workfile.
  			INTEGER(4) FUNCTION IApplication_GetGroup($OBJECT, seriesNames, sampleString, NAType, naString, seriesData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES VALUE	:: seriesNames
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
			!DEC$ ATTRIBUTES STDCALL :: IApplication_GetGroup
			END FUNCTION IApplication_GetGroup
		END INTERFACE
		POINTER(IApplication_GetGroup_PTR, IApplication_GetGroup)	! routine pointer
		INTERFACE
			!Returns data from multiple series objects in the current workfile.
  			INTEGER(4) FUNCTION IApplication_GetGroupEx($OBJECT, seriesNames, sampleString, NAType, naString, groupOptions, seriesData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES VALUE	:: seriesNames
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: groupOptions	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: groupOptions
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
			!DEC$ ATTRIBUTES STDCALL :: IApplication_GetGroupEx
			END FUNCTION IApplication_GetGroupEx
		END INTERFACE
		POINTER(IApplication_GetGroupEx_PTR, IApplication_GetGroupEx)	! routine pointer
		INTERFACE
			!Returns data from the specified series object in the current workfile.
  			INTEGER(4) FUNCTION IApplication_GetSeries($OBJECT, seriesName, sampleString, NAType, naString, seriesData)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: seriesName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: seriesName
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES VALUE	:: NAType
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: naString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: naString
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
			!DEC$ ATTRIBUTES STDCALL :: IApplication_GetSeries
			END FUNCTION IApplication_GetSeries
		END INTERFACE
		POINTER(IApplication_GetSeries_PTR, IApplication_GetSeries)	! routine pointer
		INTERFACE
			!Hides EViews window.
  			INTEGER(4) FUNCTION IApplication_Hide($OBJECT)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Hide
			END FUNCTION IApplication_Hide
		END INTERFACE
		POINTER(IApplication_Hide_PTR, IApplication_Hide)	! routine pointer
		INTERFACE
			!Hides the COM Automation Log window.
  			INTEGER(4) FUNCTION IApplication_HideLog($OBJECT)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
			!DEC$ ATTRIBUTES STDCALL :: IApplication_HideLog
			END FUNCTION IApplication_HideLog
		END INTERFACE
		POINTER(IApplication_HideLog_PTR, IApplication_HideLog)	! routine pointer
		INTERFACE
			!Utility function to convert a space delimited string into a string array.
  			INTEGER(4) FUNCTION IApplication_ListToArray($OBJECT, nameString, nameArray)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: nameString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: nameString
				TYPE (VARIANT), INTENT(OUT)	:: nameArray	
				!DEC$ ATTRIBUTES REFERENCE	:: nameArray
			!DEC$ ATTRIBUTES STDCALL :: IApplication_ListToArray
			END FUNCTION IApplication_ListToArray
		END INTERFACE
		POINTER(IApplication_ListToArray_PTR, IApplication_ListToArray)	! routine pointer
		INTERFACE
			!Returns an array of object names that match the specified pattern and/or type.
  			INTEGER(4) FUNCTION IApplication_Lookup($OBJECT, patternString, typeString, returnType, names)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: patternString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: patternString
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: typeString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: typeString
				INTEGER, INTENT(IN)	:: returnType	! LookupReturnType
				!DEC$ ATTRIBUTES VALUE	:: returnType
				TYPE (VARIANT), INTENT(OUT)	:: names	
				!DEC$ ATTRIBUTES REFERENCE	:: names
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Lookup
			END FUNCTION IApplication_Lookup
		END INTERFACE
		POINTER(IApplication_Lookup_PTR, IApplication_Lookup)	! routine pointer
		INTERFACE
			!Sends data into a new or existing object in the current workfile.
  			INTEGER(4) FUNCTION IApplication_Put($OBJECT, objectName, objectData, DataType, WriteType)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: objectName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: objectName
				TYPE (VARIANT), INTENT(IN)	:: objectData	
				!DEC$ ATTRIBUTES VALUE	:: objectData
				INTEGER, INTENT(IN)	:: DataType	! DataType
				!DEC$ ATTRIBUTES VALUE	:: DataType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES VALUE	:: WriteType
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Put
			END FUNCTION IApplication_Put
		END INTERFACE
		POINTER(IApplication_Put_PTR, IApplication_Put)	! routine pointer
		INTERFACE
			!Sends data into multiple new or existing series objects in the current workfile.
  			INTEGER(4) FUNCTION IApplication_PutGroup($OBJECT, seriesNames, seriesData, sampleString, SeriesType, WriteType)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES VALUE	:: seriesNames
				TYPE (VARIANT), INTENT(IN)	:: seriesData	
				!DEC$ ATTRIBUTES VALUE	:: seriesData
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: SeriesType	! SeriesType
				!DEC$ ATTRIBUTES VALUE	:: SeriesType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES VALUE	:: WriteType
			!DEC$ ATTRIBUTES STDCALL :: IApplication_PutGroup
			END FUNCTION IApplication_PutGroup
		END INTERFACE
		POINTER(IApplication_PutGroup_PTR, IApplication_PutGroup)	! routine pointer
		INTERFACE
			!Sends data into a new or existing series object in the current workfile.
  			INTEGER(4) FUNCTION IApplication_PutSeries($OBJECT, seriesName, seriesData, sampleString, SeriesType, WriteType)
				USE IFWINTY
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: seriesName	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: seriesName
				TYPE (VARIANT), INTENT(IN)	:: seriesData	
				!DEC$ ATTRIBUTES VALUE	:: seriesData
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: sampleString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: sampleString
				INTEGER, INTENT(IN)	:: SeriesType	! SeriesType
				!DEC$ ATTRIBUTES VALUE	:: SeriesType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES VALUE	:: WriteType
			!DEC$ ATTRIBUTES STDCALL :: IApplication_PutSeries
			END FUNCTION IApplication_PutSeries
		END INTERFACE
		POINTER(IApplication_PutSeries_PTR, IApplication_PutSeries)	! routine pointer
		INTERFACE
			!Run an EViews command.
  			INTEGER(4) FUNCTION IApplication_Run($OBJECT, commandString)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: commandString	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: commandString
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Run
			END FUNCTION IApplication_Run
		END INTERFACE
		POINTER(IApplication_Run_PTR, IApplication_Run)	! routine pointer
		INTERFACE
			!Shows EViews window.
  			INTEGER(4) FUNCTION IApplication_Show($OBJECT)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
			!DEC$ ATTRIBUTES STDCALL :: IApplication_Show
			END FUNCTION IApplication_Show
		END INTERFACE
		POINTER(IApplication_Show_PTR, IApplication_Show)	! routine pointer
		INTERFACE
			!Shows the COM Automation Log window.
  			INTEGER(4) FUNCTION IApplication_ShowLog($OBJECT)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
			!DEC$ ATTRIBUTES STDCALL :: IApplication_ShowLog
			END FUNCTION IApplication_ShowLog
		END INTERFACE
		POINTER(IApplication_ShowLog_PTR, IApplication_ShowLog)	! routine pointer
		INTERFACE
			!Authorize
  			INTEGER(4) FUNCTION IAuthorize_Authorize($OBJECT, challengeID, machineID, featuresKey)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: challengeID	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: challengeID
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: machineID	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: machineID
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: featuresKey	! BSTR
				!DEC$ ATTRIBUTES VALUE	:: featuresKey
			!DEC$ ATTRIBUTES STDCALL :: IAuthorize_Authorize
			END FUNCTION IAuthorize_Authorize
		END INTERFACE
		POINTER(IAuthorize_Authorize_PTR, IAuthorize_Authorize)	! routine pointer
		INTERFACE
			!Challenge
  			INTEGER(4) FUNCTION IAuthorize_GetChallenge($OBJECT, pChallenge)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: pChallenge	! BSTR
				!DEC$ ATTRIBUTES REFERENCE	:: pChallenge
			!DEC$ ATTRIBUTES STDCALL :: IAuthorize_GetChallenge
			END FUNCTION IAuthorize_GetChallenge
		END INTERFACE
		POINTER(IAuthorize_GetChallenge_PTR, IAuthorize_GetChallenge)	! routine pointer
		INTERFACE
			!Creates an EViews Application object.
  			INTEGER(4) FUNCTION IManager_GetApplication($OBJECT, CreateType, ShowLog, ppApp)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: CreateType	! CreateType
				!DEC$ ATTRIBUTES VALUE	:: CreateType
				LOGICAL(2), INTENT(IN)	:: ShowLog	
				!DEC$ ATTRIBUTES VALUE	:: ShowLog
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: ppApp	! IDispatch
				!DEC$ ATTRIBUTES REFERENCE	:: ppApp
			!DEC$ ATTRIBUTES STDCALL :: IManager_GetApplication
			END FUNCTION IManager_GetApplication
		END INTERFACE
		POINTER(IManager_GetApplication_PTR, IManager_GetApplication)	! routine pointer
		INTERFACE
			!Returns an EViews Application object for the specified Process ID
  			INTEGER(4) FUNCTION IManager_GetApplicationByProcess($OBJECT, pid, ppApp)
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: pid	
				!DEC$ ATTRIBUTES VALUE	:: pid
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: ppApp	! IDispatch
				!DEC$ ATTRIBUTES REFERENCE	:: ppApp
			!DEC$ ATTRIBUTES STDCALL :: IManager_GetApplicationByProcess
			END FUNCTION IManager_GetApplicationByProcess
		END INTERFACE
		POINTER(IManager_GetApplicationByProcess_PTR, IManager_GetApplicationByProcess)	! routine pointer


		! Module Procedures
		CONTAINS
			!Returns any previously set instance data.
  			INTEGER(4) FUNCTION $IApplication10_GetInstanceData($OBJECT, instanceData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(OUT)	:: instanceData	
				!DEC$ ATTRIBUTES REFERENCE	:: instanceData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 26 * INT_PTR_KIND()	! Add routine table offset
				IApplication10_GetInstanceData_PTR = $VTBL
				$RETURN = IApplication10_GetInstanceData($OBJECT, instanceData)
				$IApplication10_GetInstanceData = $RETURN
			END FUNCTION $IApplication10_GetInstanceData
			!Whether or not EViews is visible
  			INTEGER(4) FUNCTION $IApplication10_IsVisible($OBJECT, visible)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				LOGICAL(2), INTENT(OUT)	:: visible	
				!DEC$ ATTRIBUTES REFERENCE	:: visible
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 28 * INT_PTR_KIND()	! Add routine table offset
				IApplication10_IsVisible_PTR = $VTBL
				$RETURN = IApplication10_IsVisible($OBJECT, visible)
				$IApplication10_IsVisible = $RETURN
			END FUNCTION $IApplication10_IsVisible
			!Set a custom string as instance data.
  			INTEGER(4) FUNCTION $IApplication10_SetInstanceData($OBJECT, instanceData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: instanceData	
				!DEC$ ATTRIBUTES REFERENCE	:: instanceData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 27 * INT_PTR_KIND()	! Add routine table offset
				IApplication10_SetInstanceData_PTR = $VTBL
				$RETURN = IApplication10_SetInstanceData($OBJECT, instanceData)
				$IApplication10_SetInstanceData = $RETURN
			END FUNCTION $IApplication10_SetInstanceData
			!Returns data from an object from the current workfile or from an expression as a 2-dimensional array.
  			INTEGER(4) FUNCTION $IApplication8_Get2D($OBJECT, objectName, NAType, naString, objectData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: objectName	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: objectData	
				!DEC$ ATTRIBUTES REFERENCE	:: objectData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_objectName    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				$BSTR_objectName = ConvertStringToBSTR(objectName)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 22 * INT_PTR_KIND()	! Add routine table offset
				IApplication8_Get2D_PTR = $VTBL
				$RETURN = IApplication8_Get2D($OBJECT, $BSTR_objectName, NAType, $BSTR_naString, objectData)
				CALL SysFreeString($BSTR_objectName)
				CALL SysFreeString($BSTR_naString)
				$IApplication8_Get2D = $RETURN
			END FUNCTION $IApplication8_Get2D
			!Returns data from the specified series object in the current workfile as a 2-dimensional array.
  			INTEGER(4) FUNCTION $IApplication8_GetSeries2D($OBJECT, seriesName, sampleString, NAType, naString, seriesData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: seriesName	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_seriesName    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				$BSTR_seriesName = ConvertStringToBSTR(seriesName)
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 23 * INT_PTR_KIND()	! Add routine table offset
				IApplication8_GetSeries2D_PTR = $VTBL
				$RETURN = IApplication8_GetSeries2D($OBJECT, $BSTR_seriesName, $BSTR_sampleString, NAType, $BSTR_naString, seriesData)
				CALL SysFreeString($BSTR_seriesName)
				CALL SysFreeString($BSTR_sampleString)
				CALL SysFreeString($BSTR_naString)
				$IApplication8_GetSeries2D = $RETURN
			END FUNCTION $IApplication8_GetSeries2D
			!Returns a bit-flag of all EViews events that are currently on.  By default, all event types are turned off.
  			INTEGER(4) FUNCTION $IApplication9_GetEventTypeMask($OBJECT, eventTypes)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(OUT)	:: eventTypes	
				!DEC$ ATTRIBUTES REFERENCE	:: eventTypes
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 24 * INT_PTR_KIND()	! Add routine table offset
				IApplication9_GetEventTypeMask_PTR = $VTBL
				$RETURN = IApplication9_GetEventTypeMask($OBJECT, eventTypes)
				$IApplication9_GetEventTypeMask = $RETURN
			END FUNCTION $IApplication9_GetEventTypeMask
			!Sets which EViews events should be turned on.
  			INTEGER(4) FUNCTION $IApplication9_SetEventTypeMask($OBJECT, eventTypes)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: eventTypes	! EViewsEventType
				!DEC$ ATTRIBUTES REFERENCE	:: eventTypes
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 25 * INT_PTR_KIND()	! Add routine table offset
				IApplication9_SetEventTypeMask_PTR = $VTBL
				$RETURN = IApplication9_SetEventTypeMask($OBJECT, eventTypes)
				$IApplication9_SetEventTypeMask = $RETURN
			END FUNCTION $IApplication9_SetEventTypeMask
			!Utility function to convert a string array (or range) into a space delimited string.
  			INTEGER(4) FUNCTION $IApplication_ArrayToList($OBJECT, nameArray, nameString)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: nameArray	
				!DEC$ ATTRIBUTES REFERENCE	:: nameArray
				CHARACTER(LEN=*), INTENT(OUT)	:: nameString	! BSTR
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_nameString    ! BSTR
				INTEGER(4) $STATUS
				$BSTR_nameString = NULL
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 12 * INT_PTR_KIND()	! Add routine table offset
				IApplication_ArrayToList_PTR = $VTBL
				$RETURN = IApplication_ArrayToList($OBJECT, nameArray, $BSTR_nameString)
				$STATUS = ConvertBSTRToString($BSTR_nameString, nameString)
				CALL SysFreeString($BSTR_nameString)
				$IApplication_ArrayToList = $RETURN
			END FUNCTION $IApplication_ArrayToList
			!Returns data from an object from the current workfile or from an expression.
  			INTEGER(4) FUNCTION $IApplication_Get($OBJECT, objectName, NAType, naString, objectData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: objectName	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: objectData	
				!DEC$ ATTRIBUTES REFERENCE	:: objectData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_objectName    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				$BSTR_objectName = ConvertStringToBSTR(objectName)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 13 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Get_PTR = $VTBL
				$RETURN = IApplication_Get($OBJECT, $BSTR_objectName, NAType, $BSTR_naString, objectData)
				CALL SysFreeString($BSTR_objectName)
				CALL SysFreeString($BSTR_naString)
				$IApplication_Get = $RETURN
			END FUNCTION $IApplication_Get
			!Returns data from multiple series objects in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_GetGroup($OBJECT, seriesNames, sampleString, NAType, naString, seriesData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesNames
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 17 * INT_PTR_KIND()	! Add routine table offset
				IApplication_GetGroup_PTR = $VTBL
				$RETURN = IApplication_GetGroup($OBJECT, seriesNames, $BSTR_sampleString, NAType, $BSTR_naString, seriesData)
				CALL SysFreeString($BSTR_sampleString)
				CALL SysFreeString($BSTR_naString)
				$IApplication_GetGroup = $RETURN
			END FUNCTION $IApplication_GetGroup
			!Returns data from multiple series objects in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_GetGroupEx($OBJECT, seriesNames, sampleString, NAType, naString, groupOptions, seriesData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesNames
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: groupOptions	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_groupOptions    ! BSTR
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$BSTR_groupOptions = ConvertStringToBSTR(groupOptions)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 21 * INT_PTR_KIND()	! Add routine table offset
				IApplication_GetGroupEx_PTR = $VTBL
				$RETURN = IApplication_GetGroupEx($OBJECT, seriesNames, $BSTR_sampleString, NAType, $BSTR_naString, $BSTR_groupOptions, seriesData)
				CALL SysFreeString($BSTR_sampleString)
				CALL SysFreeString($BSTR_naString)
				CALL SysFreeString($BSTR_groupOptions)
				$IApplication_GetGroupEx = $RETURN
			END FUNCTION $IApplication_GetGroupEx
			!Returns data from the specified series object in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_GetSeries($OBJECT, seriesName, sampleString, NAType, naString, seriesData)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: seriesName	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: NAType	! NAType
				!DEC$ ATTRIBUTES REFERENCE	:: NAType
				CHARACTER(LEN=*), INTENT(IN)	:: naString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_seriesName    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_naString    ! BSTR
				$BSTR_seriesName = ConvertStringToBSTR(seriesName)
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$BSTR_naString = ConvertStringToBSTR(naString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 15 * INT_PTR_KIND()	! Add routine table offset
				IApplication_GetSeries_PTR = $VTBL
				$RETURN = IApplication_GetSeries($OBJECT, $BSTR_seriesName, $BSTR_sampleString, NAType, $BSTR_naString, seriesData)
				CALL SysFreeString($BSTR_seriesName)
				CALL SysFreeString($BSTR_sampleString)
				CALL SysFreeString($BSTR_naString)
				$IApplication_GetSeries = $RETURN
			END FUNCTION $IApplication_GetSeries
			!Hides EViews window.
  			INTEGER(4) FUNCTION $IApplication_Hide($OBJECT)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 8 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Hide_PTR = $VTBL
				$RETURN = IApplication_Hide($OBJECT)
				$IApplication_Hide = $RETURN
			END FUNCTION $IApplication_Hide
			!Hides the COM Automation Log window.
  			INTEGER(4) FUNCTION $IApplication_HideLog($OBJECT)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 20 * INT_PTR_KIND()	! Add routine table offset
				IApplication_HideLog_PTR = $VTBL
				$RETURN = IApplication_HideLog($OBJECT)
				$IApplication_HideLog = $RETURN
			END FUNCTION $IApplication_HideLog
			!Utility function to convert a space delimited string into a string array.
  			INTEGER(4) FUNCTION $IApplication_ListToArray($OBJECT, nameString, nameArray)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: nameString	! BSTR
				TYPE (VARIANT), INTENT(OUT)	:: nameArray	
				!DEC$ ATTRIBUTES REFERENCE	:: nameArray
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_nameString    ! BSTR
				$BSTR_nameString = ConvertStringToBSTR(nameString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 11 * INT_PTR_KIND()	! Add routine table offset
				IApplication_ListToArray_PTR = $VTBL
				$RETURN = IApplication_ListToArray($OBJECT, $BSTR_nameString, nameArray)
				CALL SysFreeString($BSTR_nameString)
				$IApplication_ListToArray = $RETURN
			END FUNCTION $IApplication_ListToArray
			!Returns an array of object names that match the specified pattern and/or type.
  			INTEGER(4) FUNCTION $IApplication_Lookup($OBJECT, patternString, typeString, returnType, names)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: patternString	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: typeString	! BSTR
				INTEGER, INTENT(IN)	:: returnType	! LookupReturnType
				!DEC$ ATTRIBUTES REFERENCE	:: returnType
				TYPE (VARIANT), INTENT(OUT)	:: names	
				!DEC$ ATTRIBUTES REFERENCE	:: names
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_patternString    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_typeString    ! BSTR
				$BSTR_patternString = ConvertStringToBSTR(patternString)
				$BSTR_typeString = ConvertStringToBSTR(typeString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 9 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Lookup_PTR = $VTBL
				$RETURN = IApplication_Lookup($OBJECT, $BSTR_patternString, $BSTR_typeString, returnType, names)
				CALL SysFreeString($BSTR_patternString)
				CALL SysFreeString($BSTR_typeString)
				$IApplication_Lookup = $RETURN
			END FUNCTION $IApplication_Lookup
			!Sends data into a new or existing object in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_Put($OBJECT, objectName, objectData, DataType, WriteType)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: objectName	! BSTR
				TYPE (VARIANT), INTENT(IN)	:: objectData	
				!DEC$ ATTRIBUTES REFERENCE	:: objectData
				INTEGER, INTENT(IN)	:: DataType	! DataType
				!DEC$ ATTRIBUTES REFERENCE	:: DataType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES REFERENCE	:: WriteType
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_objectName    ! BSTR
				$BSTR_objectName = ConvertStringToBSTR(objectName)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 14 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Put_PTR = $VTBL
				$RETURN = IApplication_Put($OBJECT, $BSTR_objectName, objectData, DataType, WriteType)
				CALL SysFreeString($BSTR_objectName)
				$IApplication_Put = $RETURN
			END FUNCTION $IApplication_Put
			!Sends data into multiple new or existing series objects in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_PutGroup($OBJECT, seriesNames, seriesData, sampleString, SeriesType, WriteType)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				TYPE (VARIANT), INTENT(IN)	:: seriesNames	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesNames
				TYPE (VARIANT), INTENT(IN)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: SeriesType	! SeriesType
				!DEC$ ATTRIBUTES REFERENCE	:: SeriesType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES REFERENCE	:: WriteType
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 18 * INT_PTR_KIND()	! Add routine table offset
				IApplication_PutGroup_PTR = $VTBL
				$RETURN = IApplication_PutGroup($OBJECT, seriesNames, seriesData, $BSTR_sampleString, SeriesType, WriteType)
				CALL SysFreeString($BSTR_sampleString)
				$IApplication_PutGroup = $RETURN
			END FUNCTION $IApplication_PutGroup
			!Sends data into a new or existing series object in the current workfile.
  			INTEGER(4) FUNCTION $IApplication_PutSeries($OBJECT, seriesName, seriesData, sampleString, SeriesType, WriteType)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: seriesName	! BSTR
				TYPE (VARIANT), INTENT(IN)	:: seriesData	
				!DEC$ ATTRIBUTES REFERENCE	:: seriesData
				CHARACTER(LEN=*), INTENT(IN)	:: sampleString	! BSTR
				INTEGER, INTENT(IN)	:: SeriesType	! SeriesType
				!DEC$ ATTRIBUTES REFERENCE	:: SeriesType
				INTEGER, INTENT(IN)	:: WriteType	! WriteType
				!DEC$ ATTRIBUTES REFERENCE	:: WriteType
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_seriesName    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_sampleString    ! BSTR
				$BSTR_seriesName = ConvertStringToBSTR(seriesName)
				$BSTR_sampleString = ConvertStringToBSTR(sampleString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 16 * INT_PTR_KIND()	! Add routine table offset
				IApplication_PutSeries_PTR = $VTBL
				$RETURN = IApplication_PutSeries($OBJECT, $BSTR_seriesName, seriesData, $BSTR_sampleString, SeriesType, WriteType)
				CALL SysFreeString($BSTR_seriesName)
				CALL SysFreeString($BSTR_sampleString)
				$IApplication_PutSeries = $RETURN
			END FUNCTION $IApplication_PutSeries
			!Run an EViews command.
  			INTEGER(4) FUNCTION $IApplication_Run($OBJECT, commandString)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: commandString	! BSTR
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_commandString    ! BSTR
				$BSTR_commandString = ConvertStringToBSTR(commandString)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 10 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Run_PTR = $VTBL
				$RETURN = IApplication_Run($OBJECT, $BSTR_commandString)
				CALL SysFreeString($BSTR_commandString)
				$IApplication_Run = $RETURN
			END FUNCTION $IApplication_Run
			!Shows EViews window.
  			INTEGER(4) FUNCTION $IApplication_Show($OBJECT)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 7 * INT_PTR_KIND()	! Add routine table offset
				IApplication_Show_PTR = $VTBL
				$RETURN = IApplication_Show($OBJECT)
				$IApplication_Show = $RETURN
			END FUNCTION $IApplication_Show
			!Shows the COM Automation Log window.
  			INTEGER(4) FUNCTION $IApplication_ShowLog($OBJECT)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 19 * INT_PTR_KIND()	! Add routine table offset
				IApplication_ShowLog_PTR = $VTBL
				$RETURN = IApplication_ShowLog($OBJECT)
				$IApplication_ShowLog = $RETURN
			END FUNCTION $IApplication_ShowLog
			!Authorize
  			INTEGER(4) FUNCTION $IAuthorize_Authorize($OBJECT, challengeID, machineID, featuresKey)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(IN)	:: challengeID	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: machineID	! BSTR
				CHARACTER(LEN=*), INTENT(IN)	:: featuresKey	! BSTR
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_challengeID    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_machineID    ! BSTR
				INTEGER(INT_PTR_KIND()) $BSTR_featuresKey    ! BSTR
				$BSTR_challengeID = ConvertStringToBSTR(challengeID)
				$BSTR_machineID = ConvertStringToBSTR(machineID)
				$BSTR_featuresKey = ConvertStringToBSTR(featuresKey)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 4 * INT_PTR_KIND()	! Add routine table offset
				IAuthorize_Authorize_PTR = $VTBL
				$RETURN = IAuthorize_Authorize($OBJECT, $BSTR_challengeID, $BSTR_machineID, $BSTR_featuresKey)
				CALL SysFreeString($BSTR_challengeID)
				CALL SysFreeString($BSTR_machineID)
				CALL SysFreeString($BSTR_featuresKey)
				$IAuthorize_Authorize = $RETURN
			END FUNCTION $IAuthorize_Authorize
			!Challenge
  			INTEGER(4) FUNCTION $IAuthorize_GetChallenge($OBJECT, pChallenge)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				CHARACTER(LEN=*), INTENT(OUT)	:: pChallenge	! BSTR
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				INTEGER(INT_PTR_KIND()) $BSTR_pChallenge    ! BSTR
				INTEGER(4) $STATUS
				$BSTR_pChallenge = NULL
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 3 * INT_PTR_KIND()	! Add routine table offset
				IAuthorize_GetChallenge_PTR = $VTBL
				$RETURN = IAuthorize_GetChallenge($OBJECT, $BSTR_pChallenge)
				$STATUS = ConvertBSTRToString($BSTR_pChallenge, pChallenge)
				CALL SysFreeString($BSTR_pChallenge)
				$IAuthorize_GetChallenge = $RETURN
			END FUNCTION $IAuthorize_GetChallenge
			!Creates an EViews Application object.
  			INTEGER(4) FUNCTION $IManager_GetApplication($OBJECT, CreateType, ShowLog, ppApp)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: CreateType	! CreateType
				!DEC$ ATTRIBUTES REFERENCE	:: CreateType
				LOGICAL(2), INTENT(IN)	:: ShowLog	
				!DEC$ ATTRIBUTES REFERENCE	:: ShowLog
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: ppApp	! IDispatch
				!DEC$ ATTRIBUTES REFERENCE	:: ppApp
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 7 * INT_PTR_KIND()	! Add routine table offset
				IManager_GetApplication_PTR = $VTBL
				$RETURN = IManager_GetApplication($OBJECT, CreateType, ShowLog, ppApp)
				$IManager_GetApplication = $RETURN
			END FUNCTION $IManager_GetApplication
			!Returns an EViews Application object for the specified Process ID
  			INTEGER(4) FUNCTION $IManager_GetApplicationByProcess($OBJECT, pid, ppApp)
				IMPLICIT NONE
	
				INTEGER(INT_PTR_KIND()), INTENT(IN)	:: $OBJECT	 ! Object Pointer
				!DEC$ ATTRIBUTES VALUE	:: $OBJECT
				INTEGER, INTENT(IN)	:: pid	
				!DEC$ ATTRIBUTES REFERENCE	:: pid
				INTEGER(INT_PTR_KIND()), INTENT(OUT)	:: ppApp	! IDispatch
				!DEC$ ATTRIBUTES REFERENCE	:: ppApp
				INTEGER(4) $RETURN
				INTEGER(INT_PTR_KIND()) $VTBL			! Interface Function Table
				POINTER($VPTR, $VTBL)
				$VPTR = $OBJECT					! Interface Function Table
				$VPTR = $VTBL + 8 * INT_PTR_KIND()	! Add routine table offset
				IManager_GetApplicationByProcess_PTR = $VTBL
				$RETURN = IManager_GetApplicationByProcess($OBJECT, pid, ppApp)
				$IManager_GetApplicationByProcess = $RETURN
			END FUNCTION $IManager_GetApplicationByProcess
	END MODULE
